version: 2.1

orbs:
  cdk: helix/cdk@dev:alpha #0.5.0

workflows:
  build:
    jobs:

      - cdk/install:
          name: "Install NPM packages for cdk"
          context: npm-readonly

      - cdk/test:
          name: "Test"
          requires:
            - "Install NPM packages for cdk"

      - cdk/lint:
          name: "Lint"
          requires:
            - "Install NPM packages for cdk"

      - cdk/build:
          name: "Build"
          requires:
            - "Install NPM packages for cdk"

      - cdk/publish:
          name: "Publish release of cdk-watchful"
          requires:
            - Test
            - Lint
            - Build
          context: npm-publish
          filters:
            branches:
              only: main

      - cdk/publish:
          name: "Publish dev build of cdk-watchful"
          npm_params: --tag -dev
          requires:
            - Test
            - Lint
            - Build
          context: npm-publish
          filters:
            branches:
              ignore: 
                - main