version: 2.1

orbs:
  cdk: myhelix/cdk@0.4.0

executors:
  node:
    docker:
      - image: cimg/node:15.10.0

jobs:
  publish:
    executor: node
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
      - run:
          name: Publish Canary if dev- branch
          command: |
            if [[ $CIRCLE_BRANCH =~ ^dev-.* ]]; then
              npm whoami
              npm version --no-git-tag-version prerelease --preid=dev  
              npm publish
            fi
      - when:
          condition:
            or:
              - equal: ["main", << pipeline.git.branch >>]
          steps:
            - run:
                name: npm publish
                command: npm publish
      - run:
          name: Clean up credentials.
          command: rm -f $HOME/.npmrc

workflows:
  build:
    jobs:
      - cdk/install:
          name: "Install NPM packages for cdk"
          context: npm-readonly

      - cdk/test:
          name: "Test"
          requires:
            - "Install NPM packages for cdk"

      - cdk/lint:
          name: "Lint"
          requires:
            - "Install NPM packages for cdk"

      - cdk/build:
          name: "Build"
          requires:
            - "Install NPM packages for cdk"

      - publish:
          name: "Publish cdk-watchful"
          requires:
            - Test
            - Lint
            - Build
          context: npm-publish
